force-app/main/default/objects/Object_A__c/Object_A__c.object-meta.xml
<CustomObject>
    <label>Object A</label>
    <nameField>
        <label>Nom de Object A</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_B__c/Object_B__c.object-meta.xml
<CustomObject>
    <label>Object B</label>
    <nameField>
        <label>Nom de Object B</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object B</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_B__c/fields/Object_A__c.field-meta.xml
<CustomField>
    <fullName>Object_A__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object A</label>
    <referenceTo>Object_A__c</referenceTo>
    <relationshipLabel>Object B</relationshipLabel>
    <relationshipName>Object_B</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_C__c/Object_C__c.object-meta.xml
<CustomObject>
    <label>Object C</label>
    <nameField>
        <label>Nom de Object C</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object C</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_C__c/fields/Object_B__c.field-meta.xml
<CustomField>
    <fullName>Object_B__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Object B</label>
    <referenceTo>Object_B__c</referenceTo>
    <relationshipLabel>Object C</relationshipLabel>
    <relationshipName>Object_C</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NatixisDataDisplayTest.cls
@isTest
public class NatixisDataDisplayTest {
    @isTest
    Public static void displayDataTest(){
        
        //create object A
        List<Object_A__c> objAs= new List<Object_A__c>();
        for(Integer j =0; j<2;j++){
            Object_A__c objA= new Object_A__c();
            objA.Name= 'Test A 1';
            objAs.add(objA);
        }
        insert objAs;
        
        //create object B
        Object_B__c objB= new Object_B__c();
        objB.Name= 'Test B 1';
        objB.Object_A__c=objAs[0].Id;
        insert objB;
        
        //create object C
        List<Object_C__c> objCs= new List<Object_C__c>();
        for(Integer j =0; j<2;j++){
            Object_C__c objC= new Object_C__c();
            objC.Name= 'Test C'+j;
            objC.Object_B__c=objB.Id;
            objC.Description__c='hello world';
            objCs.add(objC);
        }
        insert objCs;
        
        //tests result
        List<NatixisDataDisplay.FirstWrapper> result;
        List<NatixisDataDisplay.FirstWrapper> resultNull;
        Test.startTest();
        result= NatixisDataDisplay.displayData(objAs[0].Id);
        //Tests null path
        resultNull= NatixisDataDisplay.displayData(objAs[1].Id);
        Test.stopTest();
        
        //Assertions verification for result
        system.assertEquals(result.size(), 1);
        system.assertEquals(resultNull, null);
    }
}